dataset:
  name: pcbs
  format: folder
  path: ../my-dataset/GAN_cracks_100
  normal_dir: /section1/train/good # name of the folder containing normal images.
  abnormal_dir: /section1/test/bad # name of the folder containing abnormal images.
  normal_test_dir: /section1/test/good # name of the folder containing normal test images.
  task: classification # classification or segmentation
  mask: <path/to/mask/annotations> #optional
  extensions: null
  split_ratio: 0.2 # ratio of the normal images that will be used to create a test split
  image_size: 256
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 8
  transform_config:
    train: null
    val: null
  create_validation_set: true
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
